parameters:
    mcfedr_twitter_push.twitter.consumer_key: ''
    mcfedr_twitter_push.twitter.consumer_secret: ''
    mcfedr_twitter_push.twitter.token: ''
    mcfedr_twitter_push.twitter.token_secret: ''
    mcfedr_twitter_push.userid: ''
    mcfedr_twitter_push.gcm_ttl: ''
    mcfedr_twitter_push.link_placeholder: ''

services:
    mcfedr_twitter_push.twitter_stream_client:
        class: GuzzleHttp\Client
        factory_class: Mcfedr\TwitterPushBundle\DependencyInjection\GuzzleClientFactory
        factory_method: get
        arguments:
            -
                base_url:
                    - "https://stream.twitter.com/{version}/"
                    -
                        version: "1.1"
                defaults:
                    auth: oauth
            -
                - "@mcfedr_twitter_push.twitter_oauth"
                - "@mcfedr_twitter_push.twitter_stream_log_subscriber"

    mcfedr_twitter_push.twitter_oauth:
        class: GuzzleHttp\Subscriber\Oauth\Oauth1
        arguments:
            -
                consumer_key: "%mcfedr_twitter_push.twitter.consumer_key%"
                consumer_secret: "%mcfedr_twitter_push.twitter.consumer_secret%"
                token: "%mcfedr_twitter_push.twitter.token%"
                token_secret: "%mcfedr_twitter_push.twitter.token_secret%"

    mcfedr_twitter_push.command.stream:
        class: Mcfedr\TwitterPushBundle\Command\TwitterStreamCommand
        arguments:
            - "@mcfedr_twitter_push.twitter_stream_client"
            - "@mcfedr_twitter_push.pusher"
            - "%mcfedr_twitter_push.userid%"
            - "@logger"
        tags:
            -  { name: console.command }

    mcfedr_twitter_push.pusher:
        class: Mcfedr\TwitterPushBundle\Service\TweetPusher
        arguments:
            - "@mcfedr_aws_push.messages"
            - "%mcfedr_aws_push.topic_arn%"
            - "%mcfedr_twitter_push.gcm_ttl%"
            - "%mcfedr_twitter_push.link_placeholder%"

    mcfedr_twitter_push.twitter_stream_log_subscriber:
        class: GuzzleHttp\Subscriber\Log\LogSubscriber
        arguments:
            - @logger
